Nav Bar fix & Other UI stuff
scg-unibe-ch/ese2020-team5 pull request #39
Opened 2020-10-28 20:56 UTC by schnajos

2020-10-31 13:03 UTC, KnownInter requested changes
There seems to be a couple of issues:
- The logo doesn't show up
- Hovering the icons makes them invisible
- The 'Admin Dashboard' Icon is completely invisible
- Be consistent with product or listing
- The navigation bar doesn't scale properly with smaller screens
- I feel like the navigation bar takes up too much space with that height
- There are sometimes random overflows eventhough the complete height isn't in use

Overall it looks a bit too whitish. Maybe add different types of white to add some variety. And as we've discussed before, there is no need to force the design of the mockups. We can use the mockups as an orientation, so don't waste too much time implementing it. Also create a new branch for the mockups, so we can just merge it into master.

2020-10-31 13:03 UTC, KnownInter commented on frontend/src/app/app-routing.module.ts
> +  { path: 'admin/dashboard/products', component: AdminProductPanelComponent, canActivate: [AdminGuard]  },
Why did you add the additional spaces at the end?

2020-10-31 13:03 UTC, KnownInter commented on frontend/src/app/components/create-product/create-product.component.spec.ts
> +    fixture = TestBed.createComponent(CreateListingComponent);
It should be CreateProductComponent and not CreateListingComponent.

2020-10-31 13:03 UTC, KnownInter commented on frontend/src/app/components/edit-product/edit-product.component.html
> -      <mat-select formControlName="sellOrLend" [disabled]="productForm.value.type == 1 || productForm.value.priceKind == 1 || productForm.value.priceKind == 2">
Those conditions were added for a more dynamic formular. Why did you remove them?

2020-10-31 13:03 UTC, KnownInter commented on frontend/src/app/components/my-products/my-products.component.css
> +}
I don't see any usage of this.

2020-10-31 13:03 UTC, KnownInter commented on frontend/src/app/components/profile/profile.component.css
> +  }
You don't need to add a grid everywhere if you don't need it.

2020-10-31 16:56 UTC, schnajos commented on frontend/src/app/app-routing.module.ts
> +  { path: 'admin/dashboard/products', component: AdminProductPanelComponent, canActivate: [AdminGuard]  },
Oh oops, that's a mistake from pasting the adminGuard back in after disabling it 😅

2020-10-31 17:00 UTC, schnajos commented on frontend/src/app/components/profile/profile.component.css
> +  }
I didn't use it then but the page will make use of a grid, once I have all the elements figured out

2020-11-02 19:26 UTC, schnajos commented on frontend/src/app/components/my-products/my-products.component.css
> +}
In future implementation, add other views that use grid

2020-11-03 15:57 UTC, merged